from . import res_config_settings
from . import ngsign_client
from . import account_move
from . import account_tax
from . import account_payment_term
from . import ngsign_template_settings
from . import res_partner
from . import ngsign_developer_settings
from . import res_company
from . import base_document_layout
from . import ngsign_ttn_layout_settings
from . import ngsign_sign_options_wizard
from . import ngsign_pds_options_wizard
